branch-defaults:
  master:
    environment: null
global:
  application_name: Cognitive Server
  branch: null
  default_ec2_keyname: null
  default_platform: Tomcat 8 Java 8
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
deploy:
  artifact: chatbot-flygresor/target/chatbot-flygresor.war
